import { createAgent } from "langchain";
import { model } from "../configs/gemini.js";
import { NotesSchema, type NotesSchemaType } from "../schmas/notes_schema.js";
import { notesAgentPrompt } from "./prompts/prompts.js";
import { getFrame } from "./tools/image.js";
import type { State } from "./graph.js";
import { getIO } from "../webSockets/server.js";
import { Events } from "../utils/events.js";
import { logger } from "../utils/logger.js";

// Step 1: Agent without responseFormat (so it can use tools and function calling successfully on Gemini)
export const notesAgent = createAgent({
  model: model,
  systemPrompt: notesAgentPrompt,
  tools: [getFrame],
  name: "notesAgent",
});

// Step 2: Structuring LLM node (uses withStructuredOutput without tools to bypass Gemini's API constraint)
const structuringModel = model.withStructuredOutput(NotesSchema);

const events = Events.NOTES;
export const notesAgentNode = async (state: State) => {
  try {
    const io = getIO();
    if (io) {
        io.to(state.sessionId).emit(events.PROCESSING_STARTED);
    }
    logger.info(`Invoking notes LLM agent for session: ${state.sessionId}, chunkIndex: ${state.chunkIndex}`);
    const response = await notesAgent.invoke({
      messages: [
        {
          role: "user",
          content: `${JSON.stringify({ 
                videoTitle : state.videoTitle,
                transcript : state.transcript,
                rollingSummary : state.rollingSummary,
                previousTranscript : state.previousTranscript,
                startTimestamp : state.startTimestamp,
                endTimestamp : state.endTimestamp,
                sessionId : state.sessionId,
                chunkIndex : state.chunkIndex,
          })}`,
        },
      ],
    });
    logger.info(`Notes LLM agent call completed for session: ${state.sessionId}, chunkIndex: ${state.chunkIndex}`);
    
    // Extract textual response content from the agent's message trajectory
    const lastMsg = response.messages[response.messages.length - 1];
    const draftText = lastMsg && lastMsg.content
        ? (typeof lastMsg.content === 'string' ? lastMsg.content : String(lastMsg.content))
        : "No draft content generated by the agent.";

    logger.info(`Invoking structuring model to format notes for session: ${state.sessionId}, chunkIndex: ${state.chunkIndex}`);
    const structuredNotes = await structuringModel.invoke([
      {
        role: "system",
        content: `You are a precise data formatter. Your task is to take the drafted notes and format them strictly into the requested JSON schema. Make sure you set chunkIndex exactly to ${state.chunkIndex}, chapter title matching the general topic of the video lecture, and populate the topics array with blocks containing headings, paragraphs, lists, code blocks, etc. as appropriate.`
      },
      {
        role: "user",
        content: `Here are the draft notes:\n\n${draftText}`
      }
    ]);

    logger.info(`Structured formatting completed successfully for session: ${state.sessionId}, chunkIndex: ${state.chunkIndex}`);
    
    return {
        notes: structuredNotes as NotesSchemaType,
    };

  } catch (error) {
    logger.error("Error in notesAgentNode:", error);
    throw new Error(
      `Error in notesAgentNode: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
};
